services:

  kafka-1:
    image: confluentinc/cp-server:latest
    container_name: kafka-1
    networks:
      - confluent-local-network
    ports:
      - "33333:33333" 
      - "44444:44444"
      - "9093:9093"
    volumes:
      - ${KAFKA_SERVER_JAAS_CONF}:/etc/kafka/kafka_server_jaas.conf
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9093'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka-1:44444,EXTERNAL://0.0.0.0:33333, CONTROLLER://kafka-1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:44444,EXTERNAL://localhost:33333'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  

      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_COMMAND_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICATION_FACTOR: 1


  gateway:
    image: "${GATEWAY_IMAGE}"
    container_name: gateway
    networks:
      - confluent-local-network
    depends_on:
      - kafka-1
    environment:
      GATEWAY_CONFIG: | 
        gateway:
          admin:
            endpoints:
              metrics: true
          streamingDomains:
            - name: sample-domain
              type: kafka
              kafkaCluster:
                name: kafka-cluster-1
                nodeIdRanges:
                  - name: d
                    start: 1 # 19093, 1
                    end: 5
                bootstrapServers:
                  - id: localkafka
                    endpoint: "kafka-1:44444" # <----- kafka internal listener endpoint 
          routes:
            - name: passthrough
              endpoint: "host.docker.internal:19092"
              brokerIdentificationStrategy:
                type: port # nodeId starts from 19093 and for nodes starting from 1 to 5
              streamingDomain:
                name: sample-domain
                bootstrapServerId: localkafka
              security:
                auth: passthrough

    ports:
      - "19092:19092"
      - "19093:19093"
      - "19094:19094"
      - "9190:9190"
    command: |
      bash -c "
        chmod +x /etc/confluent/docker/run 2>/dev/null || true
        exec /etc/confluent/docker/run
      "

networks:
  confluent-local-network:
    driver: bridge
