#!/usr/bin/env bash

#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

echo "===> Configuring Gateway..."

# Run the configure script to validate environment
/etc/confluent/docker/configure

# exporting during configure does not persist, so we need to set it again
if [ -z "$GATEWAY_CONFIG_FILE" ]; then
  export GATEWAY_CONFIG_FILE="/etc/${COMPONENT}/gateway-config.yaml"
fi

# If GATEWAY_NODE_ID is defined and valid, replace $(gatewayNodeId)
if [[ -n "${GATEWAY_NODE_ID-}" && "${GATEWAY_NODE_ID}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
  echo "===> Replacing \$(gatewayNodeId) in configuration file with GATEWAY_NODE_ID: ${GATEWAY_NODE_ID}"
  config_content=$(<"${GATEWAY_CONFIG_FILE}")
  echo "Original configuration content:"
  echo "${config_content}"
  config_content="${config_content//\$\(gatewayNodeId\)/${GATEWAY_NODE_ID}}"
  export GATEWAY_CONFIG_FILE="/etc/${COMPONENT}/gateway-node-config.yaml"
  echo "${config_content}" > "${GATEWAY_CONFIG_FILE}"
  echo "Updated configuration content: (saved to ${GATEWAY_CONFIG_FILE}):"
  echo "${config_content}"
fi

/usr/bin/gateway-start -c $GATEWAY_CONFIG_FILE "$@"
