# Management endpoints for monitoring and metrics
management:
  bindAddress: 127.0.0.1
  port: 9093
  endpoints:
    prometheus: {}
virtualClusters:
  - name: demo
    targetCluster:
      bootstrapServers: localhost:9092
    gateways:
      - name: mygateway
        portIdentifiesNode:
          bootstrapAddress: localhost:9192
          nodeIdRanges:
            - name: pool-1
              start: 1
              end: 3
    logNetwork: false
    logFrames: false
defaultFilters: