Configuration:
  status: WARN
  
  Properties:
    Property:
      - name: LOG_DIR
        value: "${sys:gateway.log.dir:-logs}"
  
  Appenders:
    # Console Appender
    Console:
      name: Console
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%t] - %msg%n"
    
    # Main application log file
    RollingFile:
      - name: File
        fileName: "${LOG_DIR}/gateway.log"
        filePattern: "${LOG_DIR}/gateway.log.%i"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%t] - %msg%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 100MB
        DefaultRolloverStrategy:
          max: 10
      
      # Startup/Shutdown logger
      - name: StartupShutdown
        fileName: "${LOG_DIR}/gateway-startup.log"
        filePattern: "${LOG_DIR}/gateway-startup.log.%i"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} [%t] - %msg%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: 50MB
        DefaultRolloverStrategy:
          max: 5
  
  Loggers:
    # Gateway specific loggers
    Logger:
      - name: io.confluent.gateway
        level: INFO
        additivity: false
        AppenderRef:
          - ref: Console
          - ref: File
      
      # Startup/Shutdown logger
      - name: io.confluent.gateway.StartupShutdownLogger
        level: INFO
        additivity: false
        AppenderRef:
          - ref: Console
          - ref: StartupShutdown
      
      # Kroxylicious loggers
      - name: io.kroxylicious
        level: INFO
        additivity: false
        AppenderRef:
          - ref: Console
          - ref: File
      
      # Third party loggers
      - name: org.apache.kafka
        level: WARN
      - name: org.eclipse.jetty
        level: WARN
      - name: io.netty
        level: WARN
    
    # Root Logger
    Root:
      level: INFO
      AppenderRef:
        - ref: Console
        - ref: File